---
title: "Получение сведений о системе"
author: Александр Смирнов
format: 
    md:
        output-file: README.md
engine: knitr
---


## Цель работы

Получить сведения об используемой системе

## Исходные данные

1. Ноутбук ASUS X554Lj

2. ОС OpenSUSE Tumbleweed

3. Интерпретатор командной оболочки bash 5.2.15

4. Эмулятор терминала Konsole

## План

1. Ввод команд в эмулятор терминала

2. Анализ данных

## Ход работы

1. Для начала получим сведения об используемом дистрибутиве:

```{bash}
lsb_release -a
```

В результате выполнения данной команды было определён используемый дистрибутив - openSUSE Tumbleweed версии 20230227.

2. Затем получим сведения о версии ядра:

```{bash}
uname -a
```

В результате выполнения данной команды была получена версия ядра - 6.1.12-1, дата компиляции ядра - 15 февраля 2023 года.

3. Далее можно получить сведения о процессоре:

```{bash}
cat /proc/cpuinfo | grep "model name"
```

Было определено, что используемый процессор - четырёхпоточный Intel Core i3-4005U с тактовой частотой 1.7 ГГц.

4. Далее получим последние 30 строк логов системы:

```{bash}
dmesg | tail -n 30
```

## Оценка результата

В результате лабораторной работы была получена базовая информация об используемой системе.

## Вывод

Таким образом. мы научились, используя команды Linux, получать сведения о системе.
