---
title: "Применение средств и методов OSINT"
author: Александр Смирнов
format:
    md:
        output-file: README.md
engine: knitr
---

Open source intelligence (OSINT) – разведывательная дисциплина, включающая в себя поиск, выбор
и сбор разведывательной информации из общедоступных источников, а также её анализ.

Такими источниками информации могут быть:
- поисковые машины – Google, Bing, Yandex...

- специализированные поисковые системы – intelx.io, Shodan, Censys...

- порталы открытых данных – Github Awesome Lists, https://opendata.digital.gov.ru/

- материалы профильных конференций

- социальные сети, профильные блоги и т.д.

- официальные сайты компаний

## Цель работы
1. Освоить базовые подходы процессов OSINT

2. Освоить современные инструменты поиска и сбора информации

3. Освоить инструменты совместной работы в ходе аналитической деятельности

## Задание
1. Собрать информацию о компании Ред Софт

2. Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации.

3. Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.

4. Сформировать представление о рынке отечественных решений ИБ

## Ход выполнения работы

### Основная информация о компании

Полное наименование компании -- Общество с ограниченной ответственностью "Ред Софт" (ООО "Ред Софт")

Место нахождения -- 121205, г. Москва, ул. Нобеля (Сколково Инновационного Центра Тер), д. 5 этаж 2 пом. 4

Почтовый адрес -- 125124, г. Москва, 5-я ул. Ямского поля, д.5, стр.1, а/я 64

ИНН -- 9705000373

ОРГН -- 5147746028216

[Источник](https://www.e-disclosure.ru/portal/company.aspx?id=37300)

### Структура компании

Анисимов Максим Владимирович -- генеральный директор 

Урванов Евгений Васильевич -- директор по безопасности и защите государственной тайны

#### Совет директоров

Комлев Вячеслав Александрович (Председатель совета директоров) -- директор по развитию

Зотов Владимир Сергеевич

Снигирев Владимир Александрович

Ляховский Александр Александрович

Анисимов Максим Владимирович

Сидоренко Виталий Валерьевич

Новиков Андрей Валерьевич

[Источник](https://www.red-soft.ru/files/RedSoft_GodovoiOtcchet_2022.pdf)

### Основные направления деятельности компании

#### Программные продукты
Операционная система «РЕД ОС»

Система управления виртуализацией серверов и рабочих станций «РЕД Виртуализация»

Система управления ИТ-инфраструктурой «РЕД АДМ»

Система управления базами данных «Ред База Данных»

Платформа для разработки «Ред Платформа»

Решение «РЕДШлюз»

Программное средство «РЕДВАЙН» (REDWINE)

#### Цифровизация: информационные системы и прикладные решения

Сертифицированное средство для безопасной дистанционной работы «Работаем дома»

Цифровая платформа «Принудительное исполнение»

Цифровой сервис «Взыскатель»

Система электронного документооборота «РЕД ДОК»

Платформа для распределенных вычислений и обработки больших наборов данных «РЕД Квант»

#### Решения с использованием технологий искусственного интеллекта

Системы распознавания лиц Gembaface, Gembatracker

Система интеллектуальных помощников «КАДАСТР»

Система интеллектуальных помощников «Цифровая приемная»

[Источник](https://www.red-soft.ru/files/RedSoft_GodovoiOtcchet_2022.pdf)

### Стек используемых технологий

Java

Python

Django

SQL

Linux (RPM-based)

Libvirt

QEMU

Shell (Bash)

Ansible

Virtualization (HyperV/VMWare/Proxmox)

Redmine

C++

git

[Источник](https://www.red-soft.ru/ru/vacancy-ru)

### Клиенты компаниии
ПАО "Ростелеком"

"Черноморнефтегаз" Республика Крым

Государственная корпорация по организации воздушного движения в Российской Федерации

Министерство труда и занятости Оренбургской области

МФЦ Курской области

Агентство по предпринимательству и инвестициям Дагестана

Волгоградская область

Федеральная служба судебных приставов

Генеральная прокуратура Российской Федерации

Министерство обороны Российской Федерации

Министерство цифрового развития, связи и массовых коммуникаций Российской Федерации

Федеральная антимонопольная служба

Министерство юстиции Российской Федерации

Министерство транспорта Российской Федерации

Федеральное агентство воздушного транспорта

Федеральная служба исполнения наказаний

Центральный банк Российской Федерации

Федеральное агентство по поставкам вооружения, военной, специальной техники и материальных средств

Судебный департамент при Верховном суде Российской Федерации

Федеральное агентство лесного хозяйства

Федеральный фонд обязательного медицинского страхования

Федеральная служба по техническому и экспортному контролю

Федеральная служба по гидрометеорологии и мониторингу окружащей среды

Государственная корпорация по атомной энергии «Росатом»

Администрация Липецкой области

Администрация Волгоградской области

Администрация Тамбовской области

ОАО АКБ «Еврофинанс Моснарбанк»

Акционерное общество «МСП Банк»

ООО КБ «Агропромкредит»

ООО «Алмаз-Антей Телекоммуникации»

[Источник](https://www.red-soft.ru/ru/customers-ru)

### Основные веб-сайты компании и её продуктов

[Основной сайт](https://www.red-soft.ru/ru/)

[Сайт РЕД ОС](https://redos.red-soft.ru/#redos)

[Сайт РЕД Виртуализация](https://redos.red-soft.ru/product/red-virtualizatsiya/)

[Сайт РЕД АДМ](https://redos.red-soft.ru/product/redadm/)

### Публичные ресурсы компании

[Хабр](https://habr.com/ru/companies/redsoft/articles/)

[Блог РЕД СОФТ](https://red-soft.ru/ru/blogs/%D1%80%D0%B5%D0%B4-%D1%81%D0%BE%D1%84%D1%82)

[Конференция OS day](https://osday.ru/)

[Конференция Firebird Conf](https://fbconf.ru/?utm_source=hb&utm_medium=an&utm_campaign=fb20)


## Выводы

Таким образом, с помощью процесса OSINT была получена информация о компании РЕД Софт.